Fix html.sed and related scripts
ioccc-src/temp-test-ioccc pull request #2749
Opened 2024-11-06 18:15 UTC by xexyl

The file bin/html.sed has been fixed so that it works with bin/md2html.sh (which has been modified and which is used via bin/subst.entry-index.sh and output-index-inventory.sh). The script output-index-inventory.sh was already updated to use html.sed so this file has not been modified but the md2html.sh and subst.entry-index.sh scripts have, along with bin/html.sed itself.

Tested make www which rebuilt several index.html files.

Updated bin/README.md as well as bin/index.html.

Testing that all the html files now are correct wrt Nu checker will have to be done another time, however.

2024-11-06 19:56 UTC, xexyl commented
Seems things are in good order .. power finally back on and checked files. I think all is good though it's possible some were missed.

Won't be doing any more here for the day though.

2024-11-06 22:14 UTC, lcn2 requested changes
Please see the two file level comments plus the remark about the comment containing the URL in `bin/html.sed` line 19. 

Then please reconsider / resubmit.

2024-11-06 22:14 UTC, lcn2 commented on bin/md2html.sh
Regarding `-s token=value`, we suspect that if a `token` or `value` contains a vertical bar `|` symbol, then the script will likely run into problems.

That's probably OK to make the vertical bar `|` symbol invalid for `token` and `value` because the `bin/html.sed` file can substitute the vertical bar `|` symbol for the HTML escape character string `&verbar;` and work around the issue. 

We suspect that if `token` contained an equals character `=` there could be problems.  In that case have `bin/html.sed` replace the equals character `=` with HTML escape character string `&equals;`.

The percent character `%` is also problematic, especially if `token` ends in a character `%`, or has a double percent character `%`, and so on. In that case have `bin/html.sed` replace the equals character `%` with HTML escape character string `&percnt;`.

You will need to put a NOTE about not allowing for a certain characters in the usage message **AND** you will need to restore check for those characters in the arg processing for `-s`. 

We also suggest that the comment phase of "important improvements" is better phrased "useful improvements" as that would much better highlight that useful contribution.

2024-11-06 22:48 UTC, xexyl commented
Will have to do that tomorrow. 

Power out again. Even if it wasn't though I am too tired. Woke up quite early today. 

If I have any questions here I will let you know. It seems like I might.

2024-11-06 22:49 UTC, xexyl commented
Oh the three lines. That was testing something. I accidentally marked it resolved. I was hoping it would let me commit it. Tomorrow.

2024-11-07 07:16 UTC, lcn2 commented
> Oh the three lines. That was testing something. I accidentally marked it resolved. I was hoping it would let me commit it. Tomorrow. 

Not sure what you mean by 3 lines. The edits needed are certainly more than 3 lines. 

If needed, we can perform the mods when we are back within stable WiFi range.

2024-11-07 14:54 UTC, xexyl commented
> > Oh the three lines. That was testing something. I accidentally marked it resolved. I was hoping it would let me commit it. Tomorrow.
> 
> Not sure what you mean by 3 lines. The edits needed are certainly more than 3 lines.

You mentioned there should be two lines, not three. I have fixed this but not yet committed. I have some questions on the other one though so I'll reply to that comment.

> 
> If needed, we can perform the mods when we are back within stable WiFi range.

Might or might not be needed. For the specific README.md file and the sed script definitely not. Unsure about the other one yet.

2024-11-07 14:56 UTC, xexyl commented on 1986/bright/README.md
This part has been fixed. Have to reply to the other one to get a better idea (or to confirm I understand what you're saying).

2024-11-07 14:57 UTC, xexyl commented on bin/md2html.sh
The comments part has been updated. I'll look at the other parts now too. Some I might have to ask questions about but have to look at the parts that are clear first.

2024-11-07 15:02 UTC, xexyl commented on bin/md2html.sh
A diff for html.sed is:

```diff
diff --git i/bin/html.sed w/bin/html.sed
index b6caaa991c4c62fd40f31637ad6a40f33e4df8fc..86837bf3ad7f8aa2ba738195050f8b58f34f10d4 100644
--- i/bin/html.sed
+++ w/bin/html.sed
@@ -32,5 +32,8 @@
 # other substitutions have '&'s in them and if the '&amp;' came after it would
 # corrupt the '&'s in the string.
 s/&/\\\&amp;/g
 s/</\\\&lt;/g
 s/>/\\\&gt;/g
+s/|/\\\&verbar;/g
+s/=/\\\&equals;/g
+s/%/\\\&/&percnt;/g

```

Now as for the blocking the other characters I think I need to look at the diff (or the copy I have on the server) and then add it back but for not only the ones I removed but add the ones you suggested too. I can do that and then do a `make www` to test it. That as you know takes some time and I have to go afk soon too (I think) so it'll be a while before it's done but I hope to resolve this today.

2024-11-07 15:20 UTC, xexyl commented on bin/md2html.sh
I have restored the check for the `=` in the token and the `%` in the `token` as well.

I have added a check for `token` AND `value` for the pipe symbol.

I have updated the notes and I have updated the version.

Now I have to do `make www`. If all is good I'll commit it all.

2024-11-07 15:23 UTC, xexyl commented
Now that those checks are added back, the new one is added, the USAGE is updated and the comments updated (in both of the scripts I updated, not counting the sed script), I am running `make www`. Hopefully all will be well. It'l take a while of course but if all is well I'll make a commit and then things should be good to go.

I don't know what else I'll do today here but I will sync jparse to mkiocccentry in a bit. I will hopefully be able to look at some random html pages and also verify that Nu checker works fine on all pages, using their jar file and the script I wrote that uses it to verify that files are good.

I'll be going afk soon and there will be other times when I'm afk too but that doesn't really matter.

2024-11-07 17:02 UTC, xexyl commented on bin/md2html.sh
Unfortunately a check for a semicolon was added, it seems by mistake, and that's not going to work. So I have to fix it and run `make www` again.

2024-11-07 17:30 UTC, xexyl commented
Okay the ampersand check also has to be removed .. of course. Hopefully this will be the last change needed. I added the changes back based on your comments, maybe misunderstanding, but I hope this will be the last change required. This time I'll think about any other characters that might be needed.

2024-11-07 18:44 UTC, xexyl commented
I believe commit 6fa0f7b69a988758313cfd3594447fd2239eda86 resolves the problems. Note that '&' and ';' cannot be disallowed which I know that at least one of them used to be. This is of course because html entities include those characters.

2024-11-07 18:44 UTC, xexyl commented
If I need to do anything else then please let me know. Very possibly won't do it today though.

2024-11-07 22:04 UTC, lcn2 approved these changes
Looks OK from afar and without the ability to run the code. 👍

2024-11-07 22:04 UTC, merged

2024-11-07 22:05 UTC, xexyl commented on bin/html.sed
> +#       https://www.w3schools.com/html/html_entities.asp
The format looks terrible but if you wish me to update it to that I can - tomorrow.

2024-11-07 22:06 UTC, xexyl commented on bin/html.sed
> +#       https://www.w3schools.com/html/html_entities.asp
What about this instead? If it looks good to you.

https://www.freeformatter.com/html-entities.html

2024-11-07 22:07 UTC, xexyl commented on bin/html.sed
> +#       https://www.w3schools.com/html/html_entities.asp
No that won't work. They are missing some or have only numbers, not words.

2024-11-07 22:08 UTC, xexyl commented on bin/html.sed
> +#       https://www.w3schools.com/html/html_entities.asp
The second link that is. I can update it. Probably not worth the time trying to find one that looks better..

2024-11-07 22:11 UTC, xexyl commented on bin/html.sed
> +#       https://www.w3schools.com/html/html_entities.asp
I went ahead and did it now.